### PR TITLE
Libcontainer networking

### PR DESCRIPTION
**Pull request by fabiokung**
Make containers spawned by the libcontainer driver stop attaching to the `docker0` bridge. The driver now manages its own networking.

~~A random tcp port and ip address (based on the container unique `UID`) is generated for each container, and port mapping is configured with `iptables`.~~ - After some thought, port allocation isn't really necessary $PORT can be decided outside of hsup and passed in as the $PORT config var.

### CODE REVIEW

**Comment by sclasen** [comment]
Looking good.  

Seems like we will need to add returning IP/Port from DynoDriver.Start to all the drivers, or come up with some other way of propagating the ip/ports back to where the control-api can get at them....or restructure how the control-api works /cc @fdr

**Comment by fabiokung** [comment]
IIUC the idea is that these things can be propagated back inside/via the `Executor`.

**Comment by sclasen** [comment]
yeah so we return IP/Port from DynoDriver.Start here then?

https://github.com/heroku/hsup/blob/libcontainer-networking/executor.go#L95

**Comment by fabiokung** [comment]
> yeah so we return IP/Port from DynoDriver.Start

we could, yes. But I think that with how things are currently designed, we are supposed to stuff those things into the executor (like [these](https://github.com/heroku/hsup/blob/libcontainer-networking/executor.go#L39-L58), for example), which the control api will have access to, here:

https://github.com/heroku/hsup/blob/libcontainer-networking/processes.go#L26

**Comment by sclasen** [comment]
aha got it.

**Comment by fdr** [comment]
I skimmed this.  I like the stuff you've done with the (now dual-purposed) resource allocator.

What I can't so easily assess is why a bunch of the networking stuff is present.  Like, what's the goal to be solved, and how the ream of mechanism to get there serves that goal.

**Comment by fabiokung** [comment]
> What I can't so easily assess is why a bunch of the networking stuff is present. Like, what's the goal to be solved, and how the ream of mechanism to get there serves that goal.

The primary goal is to provide network isolation between containers, and between containers and the host. There are multiple ways of doing that and layer3 only  (no layer2) provides a very high level of isolation. By default there is no way for containers to be sniffing traffic from each other and/or do broadcast.

There currently is no use case for layer2 networking between containers, then no need for us to be managing a bridge between containers in a secure way. Not doing any layer2 is just simpler.

I can provide more context about any of the particular implementation details, but this is the main motivation. Anything in particular you feel need better explanation/context?

**Comment by fdr** [comment]
On Wed, Feb 18, 2015 at 3:37 PM, Fabio Kung <notifications@github.com>
wrote:

> What I can't so easily assess is why a bunch of the networking stuff is
> present. Like, what's the goal to be solved, and how the ream of mechanism
> to get there serves that goal.
>
> The primary goal is to provide network isolation between containers, and
> between containers and the host. There are multiple ways of doing that and
> layer3 only (no layer2) provides a very high level of isolation. By default
> there is no way for containers to be sniffing traffic from each other
> and/or do broadcast.
>
> There currently is no use case for layer2 networking between containers,
> then no need for us to be managing a bridge between containers in a secure
> way. Not doing any layer2 is just simpler.
>
> I can provide more context about any of the particular implementation
> details, but this is the main motivation. Anything in particular you feel
> need better explanation/context?
>
Although it doesn't directly answer your question, the reason I asked these
questions is that while glossing over your code I asked myself "do I
understand why this code exists and how it fits into some goal."  So, I'm
not really working my way towards any point, I'm merely engaging in some
critical self-reflection in how well I understand any piece of the patch.

I think part of the problem is I should read the patch cumulatively.  I'll
do that next.

**Comment by fabiokung** [comment]
> I think part of the problem is I should read the patch cumulatively.  I'll do that next.

Cool. Yes, I think that reading individual commits (and their messages) may help understanding particular choices.

**Comment by fdr** [comment]
Other way around.  The small commits don't work so well for me when I don't grasp the whole.  As a contrived example, https://github.com/heroku/hsup/commit/11de2c07fc267ce70cb605e6c399cbe083bbca33: what use is the code before vs after?  It sounds like nothing would work in an anticipated way without it.  Or https://github.com/heroku/hsup/commit/c57e5cf6f7bd95824800f6670a0213d846e43540

**Comment by fabiokung** [comment]
OK. About these two spefically, yes @11de2c07fc is a requirement for everything else, and @c57e5cf6f7bd9 is just a sanity check.

**Comment by fabiokung** [comment]
rebased against master

**Comment by fabiokung** [comment]
This is now ready to be merged. Previous behavior (static IP, attach to a bridge) can be retained with some special env vars:

```sh-session
$ sudo HSUP_CONTROL_DIR=$(pwd)/hsctl LIBCONTAINER_DYNO_IP="172.17.0.101/16" LIBCONTAINER_GW_IP="172.17.42.1" LIBCONTAINER_BRIDGE="docker0" hsup run -d libcontainer -- bash
```

I also got rid of the port allocation stuff. After some thought, I realized that it's not necessary. Containers get unique IPs in different subnets, so they can bind to whatever tcp port they want. If a specific `$PORT` needs to be allocated for a particular app/dyno, it can be done outside of hsup and passed in as the `$PORT` config (env) var.

/cc @sclasen @dpiddy +1?

**Comment by fabiokung** [comment]
port mapping is also not necessary, as requests will come from inside the same host that is running the containers.

**Comment by sclasen** [comment]
Looks good to me! :+1:  And hey look at that Godeps diffs are supressed, go github.

**Comment by dpiddy** [comment]
:+1: :+1: :+1:

**Pull request merged**
