### PR TITLE
libcontainer driver: don't run user code as root

### PR DESCRIPTION
**Pull request by fabiokung**
Allocate unique UIDs for each container and run containers as unprivileged users.

/cc @fdr we may want to do something similar for the Docker driver. Without user namespaces, if processes somehow manage to escape their namespaces, they will be able to access other containers' resources/data, even without escalating to root, because they all run as the same user (uid=1000).

### CODE REVIEW

**Comment by sclasen** [comment]
nice work!

**Comment by fdr** [comment]
Interesting point.  I have been struggling with the issue of UID/GIDs when it comes to file sharing, in particular to make it match the host machine, say, read sources, for example.  I'd like to avoid an extra structure in the Docker driver (e.g. the "uid dir"), which understandably imposes less penalty on the libcontainer driver which already has to build some directory structures to make other stuff happen.

So, I'm undecided, but thanks for flagging my attention: the matters of UID/GID have been on my mind for different reasons that perhaps can be bent to serve both.

**Comment by fdr** [comment]
Oh yeah, feel free to merge this once you've checked over the work and commit messages/history in particular.  The changes to the architecture writ large are non-existent and I don't want to block your other work.  I'll try to give it a review in the spirit of finding bugs and things.

**Comment by dpiddy** [comment]
Awesome!

**Pull request merged**
