### PR TITLE
initial pass at using a unix socket for status api and bubbling up ip/port

### PR DESCRIPTION
**Pull request by sclasen**
/cc @fabiokung @fdr this about the right way to do this?

how do we surface an ip and port correctly from the other drivers?

### CODE REVIEW

**Comment by sclasen** [comment]
the unix socket side of things works, just need to figure out what values to fill in for IPAddress and Port for each executor

**Comment by sclasen** [comment]
and btw, `curl-unix-socket` is pretty fiddly with args, unlike curl

assuming `--control-socket=/tmp/hsup.sock` 

use 

```
curl-unix-socket -v -X POST  -d '{"Processes":["processType"]}'  unix:///tmp/hsup.sock:/control/stop
```

to stop the process named `processType`

**Comment by fdr** [comment]
Something that has been bugging me for a while is the Status API is liable to have data races.

You can probably see this by compiling with `go install -race` and see when you do stuff like kill a process (which causes the `Executor.Tick()` to go through the restart process and touch some private state will subsequently trip the race detector).

The way I typically solve this is by synchronization and locking long enough to copying memory for readers.  Example [Reader](https://github.com/heroku/hsup/blob/833bff9c8d09665c4c1001505a355ad0d6640d9c/diag/diagnostic.go#L96-L101),  [Modifier](https://github.com/heroku/hsup/blob/833bff9c8d09665c4c1001505a355ad0d6640d9c/diag/diagnostic.go#L54-L55) that holds the locks under more complex operations.

You might try other approaches like somehow synchronizing a request for status through `.Trigger()` and `.Tick()`, but I somewhat suspect that will come out strangely.

**Comment by fdr** [comment]
I'm looking to do something about the race conditions but I can't seem to compile with "godep go test".  It looks like a dependency problem:

```
./libcontainer_dyno_driver.go:35: undefined: network.AddStrategy
./libcontainer_dyno_driver.go:231: cannot use subnet.Host().IP (type net.IP) as type string in assignment
```

**Comment by daneharrigan** [comment]
is this PR still valid? should it be rebased or redone?

**Comment by sclasen** [comment]
closed in favor of #28

**Pull request closed without merging**
